### ISSUE TITLE
The script breaks when archillect-count is 41

### ISSUE THREAD

**Issue by bvanrijn** [bvanrijn/archillect#1]
The script breaks when archillect-count is 41. A fix without changing any code is to update archillect-count manually:

    echo 41 > archillect-count.txt

```
Traceback (most recent call last):
  File "bots/xenial/archillect.py", line 32, in <module>
    bot.sendPhoto('@archillect', photo=image)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 121, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 147, in decorator
    result = request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 63, in decorator
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 144, in post
    data = InputFile(data)
  File "/usr/local/lib/python2.7/dist-packages/telegram/inputfile.py", line 94, in __init__
    self.mimetype = mimetypes.guess_type(self.filename)[0] or DEFAULT_MIME_TYPE
  File "/usr/lib/python2.7/mimetypes.py", line 298, in guess_type
    return _db.guess_type(url, strict)
  File "/usr/lib/python2.7/mimetypes.py", line 114, in guess_type
    scheme, url = urllib.splittype(url)
  File "/usr/lib/python2.7/urllib.py", line 1074, in splittype
    match = _typeprog.match(url)
TypeError: expected string or buffer
```

**Comment by bvanrijn** [comment]
Seems to happen with 255 too.

**Comment by bvanrijn** [comment]
This just... totally... unexpectedly happened with `2195`. 

```
Traceback (most recent call last):
  File "archillect.py", line 18, in <module>
    bot.sendPhoto('@archillect', photo=str(image_url), caption='>> @archillect <<')
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 121, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 147, in decorator
    result = request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 227, in post
    data = InputFile(data)
  File "/usr/local/lib/python2.7/dist-packages/telegram/inputfile.py", line 73, in __init__
    self.input_file = urlopen(self.input_file)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", Traceback (most recent call last):
  File "archillect.py", line 18, in <module>
    bot.sendPhoto('@archillect', photo=str(image_url), caption='>> @archillect <<')
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 121, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 147, in decorator
    result = request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 227, in post
    data = InputFile(data)
  File "/usr/local/lib/python2.7/dist-packages/telegram/inputfile.py", line 73, in __init__
    self.input_file = urlopen(self.input_file)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```

The usual fix applies.

**Comment by bvanrijn** [comment]
2362 too. I should try except this.

**Comment by bvanrijn** [comment]
2380
